apiVersion: v1
kind: Pod
metadata:
  name: first-pod
spec:
  containers:
    - name: first-container
      image: nginx
      command:
        - "sh"
        - "-c"
        - "echo Hello Kubernetes! && sleep 3600"
      ports:
        - containerPort: 80

