pipeline {
    agent { label 'java-node' }

    stages {
        stage('Build') {
            tools {
                jdk 'JDK17'
                maven 'maven'
            }

            steps {
                sh 'java -version'
                sh 'mvn -version'
                sh 'mvn clean package'
            }
        }

        stage('Test') {
            agent { label 'java-agent-slave' }
            steps {
                echo 'Testing...'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }
}
