pipeline {

    agent {
        label 'java-node'
    }

    tools {
        jdk 'JDK17'
        maven 'maven'
    }

    options {

        buildDiscarder(
            logRotator(
                numToKeepStr: '3',
                artifactNumToKeepStr: '3'
            )
        )

        disableConcurrentBuilds()

        timestamps()

        timeout(
            time: 40,
            unit: 'MINUTES'
        )
    }


    environment {

        IMAGE_NAME = "spring-petclinic"
        IMAGE_TAG  = "${BUILD_NUMBER}"

        MAVEN_OPTS = "-Xmx1024m -Xms512m"
    }


    stages {


        stage('Checkout') {

            steps {

                cleanWs()

                git branch: 'main',
                    url: 'https://github.com/spring-projects/spring-petclinic.git'
            }
        }


        stage('Build') {

            steps {

                sh '''
                    java -version
                    mvn -version

                    mvn clean compile
                '''
            }
        }


        stage('Test') {

            steps {

                sh '''
                    docker ps

                    mvn test \
                    -Dspring.docker.compose.skip.in-tests=false \
                    -DforkCount=1 \
                    -DreuseForks=false
                '''
            }


            post {

                always {

                    junit(
                        allowEmptyResults: true,
                        testResults: 'target/surefire-reports/*.xml'
                    )
                }
            }
        }



        stage('SonarQube Analysis') {

            steps {

                withSonarQubeEnv('SonarQube') {

                    sh '''

                    mvn sonar:sonar \
                    -Dsonar.projectKey=spring-petclinic \
                    -Dsonar.projectName=spring-petclinic

                    '''
                }
            }
        }



        stage('Quality Gate') {

            steps {

                timeout(
                    time:10,
                    unit:'MINUTES'
                ){

                    waitForQualityGate(
                        abortPipeline:true
                    )
                }
            }
        }



        stage('Package') {

            steps {

                sh '''

                mvn package -DskipTests

                '''
            }
        }




        stage('Docker Build') {

            steps {

                sh '''

                docker build \
                -t ${IMAGE_NAME}:${IMAGE_TAG} .

                docker images | grep ${IMAGE_NAME}

                '''
            }
        }




        stage('Deploy') {

            steps {

                echo "Deployment Successful"

            }
        }

    }



    post {


        always {

            echo "Cleaning docker test containers"

            sh '''
            docker compose down -v || true
            docker rm -f petclinic-postgres || true
            '''

            echo "Cleaning workspace"

            cleanWs()
        }


        success {

            echo "Pipeline completed successfully"
        }


        failure {

            echo "Pipeline failed"
        }

    }

}
